version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: hospital-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hospital-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hospital-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - hospital-network

volumes:
  rabbitmq_data:
  sqlserver_data:

networks:
  hospital-network:
    driver: bridge
